### ISSUE TITLE
无法使用nb-cli安装

### ISSUE THREAD

**Issue by HAKURELING** [nikissXI/nonebot_plugins#1]
![image](https://user-images.githubusercontent.com/63252182/211177503-e81f9e28-661a-4cdf-828c-b1e074ce1f0b.png)
直接用nb-cli安装会提示找不到插件
如果直接clone的话，是直接把nonebot_plugin_setu_customization文件夹放进plugins文件夹么？
![image](https://user-images.githubusercontent.com/63252182/211177770-b31d4413-953f-4045-9352-242619689988.png)

**Comment by nikissXI** [comment]
mix佬说要执行一次nb plugin list刷新缓存才能看到新插件，你自己克隆到本地的话把依赖装上就行
