### ISSUE TITLE
[BUG] 不使用nonebot全局配置中的命令起始符

### ISSUE THREAD

**Issue by chenxi-Eumenides** [nikissXI/nonebot_plugins#10]
## bug

命令不使用全局配置中的COMMAND_START配置

## 期望的结果

在全局配置中开启如下配置后
COMMAND_START=["/"]
使用“/信息”来获取服务器信息，而不是"信息"。

**Comment by nikissXI** [comment]
因为用的是fullmatch，我改成on_command吧，你更新一下插件就行
![image](https://user-images.githubusercontent.com/31379266/218245379-60f2950c-e5ce-40f5-b48e-80609c73925c.png)
