### ISSUE TITLE
starlette依赖问题

### ISSUE THREAD

**Issue by Raycoi** [nikissXI/nonebot_plugins#11]
在nonebot里fastapi需要python starlette依赖0.25.0但setu插件需要0.19.1 冲突了 大佬该怎么解决

**Comment by Raycoi** [comment]
![IMG_20230301_003030](https://user-images.githubusercontent.com/112241195/221916698-9021bdf9-4b29-4d52-a2f0-779533e96f67.jpg)
日志报错

**Comment by nikissXI** [comment]
更新了1.16.1，再试试
