### ISSUE TITLE
setu_customization插件配置过程出现的问题

### ISSUE THREAD

**Issue by Raudience** [nikissXI/nonebot_plugins#12]
![image](https://user-images.githubusercontent.com/52769726/222916785-493103b3-bdd0-400b-a7f3-88c2ffbf6dcf.png)
纯小白，怎么修改.env文件，直接复制粘贴在.env文件的底部吗，大佬救救

**Comment by nikissXI** [comment]
需要配置什么就复制什么进去，然后填
