### ISSUE TITLE
群聊中不能正确返回图片

### ISSUE THREAD

**Issue by Amber-siley** [nikissXI/nonebot_plugins#15]
操作系统：Windows server 2012 r2(腾讯云)
python版本：3.10.10
**在私聊中能正确返回图片**
![Screenshot_2023_0331_142637](https://user-images.githubusercontent.com/75154201/229041387-57964b53-f887-432c-9c67-2f1f3031ed56.jpg)
**在群聊中不能正确返回图片**
![Screenshot_2023_0331_142618](https://user-images.githubusercontent.com/75154201/229041477-f546628a-c688-4178-b0cd-e3a85d696ecd.png)
![Screenshot_20230331_142605](https://user-images.githubusercontent.com/75154201/229041491-9b9a083a-4a92-4a5c-ac3b-13f2a114bf12.jpg)
**env配置，tutu_data.json配置及这两次测试日志**
![Q5OXW4ZU9}C8W`VUN_XNORQ](https://user-images.githubusercontent.com/75154201/229042390-a068193f-4555-4cb1-9a52-02b8512ba512.png)
)
![$ R~CWFIVE(HAF4B{_F9~7D](https://user-images.githubusercontent.com/75154201/229042553-e4dcbede-48c8-4331-8022-9d4ffaf66e1b.png)

**Comment by nikissXI** [comment]
我刚测试了一下，在镜像站下载的可能不是最新版，我刚更新了1.6.3，你可以clone插件代码到插件目录导入。
接口的话你添加进去后先试试返回的图片url是否能正常打开。
如果出现cq码直接发了出来，就是图片下载超时了，可以看看gocq那边的日志

**Comment by nikissXI** [comment]
刚升级1.7.0了，修复了一个导致图片发送很慢的逻辑

**Comment by Amber-siley** [comment]
用nb plugin update 升级到1.7版本，返回消息确实变快了，但是图片没了，私聊也无法返回图片了
有时候回返回cq码，有时候只有编号信息，群聊信息也是一样
![Screenshot_2023_0331_170602](https://user-images.githubusercontent.com/75154201/229077387-6ee540dd-e8a2-4056-95f4-f67d9849f55f.jpg)
![Screenshot_2023_0331_170633](https://user-images.githubusercontent.com/75154201/229077410-208689a9-fd30-4660-98c8-71566a522ed9.png)
gocq的日志信息

> [2023-03-31 17:01:34] [WARNING]: 警告: 私聊 2767145231 图片上传失败: image type error: application/octet-stream 
> [2023-03-31 17:01:34] [WARNING]: 警告: 私聊 2767145231 图片上传失败: image type error: application/octet-stream 
> [2023-03-31 17:01:34] [WARNING]: 警告: 私聊 2767145231 图片上传失败: image type error: application/octet-stream 
> [2023-03-31 17:02:00] [WARNING]: 警告: 私聊 2767145231 图片上传失败: image type error: application/octet-stream 
> [2023-03-31 17:02:00] [WARNING]: 警告: 私聊 2767145231 图片上传失败: image type error: application/octet-stream 
> [2023-03-31 17:02:00] [WARNING]: 警告: 私聊 2767145231 图片上传失败: image type error: application/octet-stream 
> [2023-03-31 17:04:10] [WARNING]: 转换消息 [CQ:image,file=https://i0.wp.com/tvax1.sinaimg.cn//large/ec43126fgy1h4qlqegn9rj21ab0wrx6p.jpg,type=,cache=true,proxy=true,timeout=10] 到MiraiGo Element时出现错误: context deadline exceeded (Client.Timeout or context cancellation while reading body). 
> [2023-03-31 17:04:15] [WARNING]: 转换消息 [CQ:image,file=https://i0.wp.com/tvax1.sinaimg.cn//large/ec43126fgy1h0nn8jq7faj214m1jux6p.jpg,type=,cache=true,proxy=true,timeout=10] 到MiraiGo Element时出现错误: context deadline exceeded (Client.Timeout or context cancellation while reading body). 
> [2023-03-31 17:04:16] [WARNING]: 警告: 合并转发 673092704 图片上传失败: image type error: application/octet-stream 
> [2023-03-31 17:04:33] [WARNING]: 转换消息 [CQ:image,file=https://i0.wp.com/tvax1.sinaimg.cn//large/ec43126fgy1h4qlh7jw32j21jk256u12.jpg,type=,cache=true,proxy=true,timeout=10] 到MiraiGo Element时出现错误: context deadline exceeded (Client.Timeout or context cancellation while reading body). 
> [2023-03-31 17:04:33] [WARNING]: 转换消息 [CQ:image,file=https://i0.wp.com/tvax1.sinaimg.cn//large/ec43126fgy1h20h551p6kj214e1l47wh.jpg,type=,cache=true,proxy=true,timeout=10] 到MiraiGo Element时出现错误: context deadline exceeded (Client.Timeout or context cancellation while reading body). 
> [2023-03-31 17:04:33] [WARNING]: 转换消息 [CQ:image,file=https://i0.wp.com/tvax1.sinaimg.cn//large/ec43126fgy1gwil03ccm9j21ww2pgnpf.jpg,type=,cache=true,proxy=true,timeout=10] 到MiraiGo Element时出现错误: context deadline exceeded (Client.Timeout or context cancellation while reading body). 
> [2023-03-31 17:06:13] [WARNING]: 警告: 合并转发 673092704 图片上传失败: image type error: application/octet-stream 
> [2023-03-31 17:06:14] [WARNING]: 警告: 合并转发 673092704 图片上传失败: image type error: application/octet-stream 
> [2023-03-31 17:06:14] [WARNING]: 警告: 合并转发 673092704 图片上传失败: image type error: application/octet-stream

**Comment by nikissXI** [comment]
换个接口试试吧，别纠结于这个接口，这接口返回图片速度不稳定导致超时

**Comment by Amber-siley** [comment]
ok 已解决
