### ISSUE TITLE
用了两天突然报错

### ISSUE THREAD

**Issue by noc228076** [nikissXI/nonebot_plugins#17]
![-45689c39f03c3f95](https://user-images.githubusercontent.com/107999044/232279136-cecd3881-08c9-43c7-a215-e3b55f08fd86.jpg)
是因为用这种方法访问gpt不稳定吗

**Comment by nikissXI** [comment]
目前gpt那个反代是出问题了，我后续看看怎么解决。

**Comment by nikissXI** [comment]
自建一个代理就行了，我写在文档了

**Comment by nikissXI** [comment]
现在更新了一个内置代理，可以直接用的

**Comment by noc228076** [comment]
> 现在更新了一个内置代理，可以直接用的

作者辛苦了
