### ISSUE TITLE
很高兴我跑通了这个机器人

### ISSUE THREAD

**Issue by DuanShaoCheng** [nikissXI/nonebot_plugins#18]
我对这个机器人有个小建议，可不可以增加前缀，不要一 at 就发言，因为我的机器人上还跑着一些其他指令，这样就会出现冲突，建议增加个配置项吧，不要强制被at就触发指令。

**Comment by nikissXI** [comment]
好，这就加上

**Comment by nikissXI** [comment]
已更新0.4.1，增加开关了，具体看文档
