### ISSUE TITLE
这个机器人还存在一个问题，文档中标注的配置与使用的配置名称不一致吧

### ISSUE THREAD

**Issue by DuanShaoCheng** [nikissXI/nonebot_plugins#19]
实际使用的变量是 talk_with_chatgpt_talk_cmd
文档中标注的变量是 talk_with_chatgpt_start_cmd

**Comment by nikissXI** [comment]
噢，抱歉，这就更新文档！

**Comment by DuanShaoCheng** [comment]
qq群可以加我一下吗，一起交流下~~ 我最近刚看机器人挺好玩的

**Comment by nikissXI** [comment]
哪个QQ群，nb用户群你直接加就行768887710
