### ISSUE TITLE
插件无法使用

### ISSUE THREAD

**Issue by Reversedeer** [nikissXI/nonebot_plugins#2]
作者写好之后有测试吗，这个插件根本无法查询服务器信息，看源码也没看见用api来查询，总之是无法使用
![image](https://user-images.githubusercontent.com/87823528/212043692-1da9da1e-dd11-423a-b59d-c0f421e839e3.png)

**Comment by nikissXI** [comment]
我今晚看看，只用自己的服务器测过

**Comment by Reversedeer** [comment]
也可能是查询的api失效了，但是我找不到api的存在

**Comment by nikissXI** [comment]
不是用API查的，用tcp连接的，我现在排查一下问题，谢谢反馈

**Comment by nikissXI** [comment]
插件查询代码进行重构了，现在支持java和基岩的查询，测试过以下服务器都可以正常使用
VoxelUtopia.com  play.xprmc.top  mc.hypixel.net  mc.nikiss.top
新版本需要配置一下.env文件，具体看一下readme

**Comment by nikissXI** [comment]
商店通过新版插件了，可以试试看

**Comment by Reversedeer** [comment]
我昨天安装插件后遇到了bug
![image](https://user-images.githubusercontent.com/87823528/212617640-fd21c5ba-2f08-42e2-88dd-ba6840c6602d.png)

**Comment by nikissXI** [comment]
你卸了我这插件，重新安装一下试试
噢噢，我的锅，你要不换Python3.10（如果可以的话），我之前没留意，这个写法得py3.10才支持

**Comment by Reversedeer** [comment]
az,那能不能适配一下其他版本的python ,qwq
因为py10有点问题，与其他插件不会互相兼容

**Comment by nikissXI** [comment]
> az,那能不能适配一下其他版本的python ,qwq 因为py10有点问题，与其他插件不会互相兼容

好吧，那我今晚改一下写法，到时候这里通知你

**Comment by Reversedeer** [comment]
嗯，建议作者使用3.8或3.9（正在用），把issue打开吧

**Comment by nikissXI** [comment]
发新版了，支持3.8以及上。如果能用了就麻烦回个信息
