### ISSUE TITLE
如何一次清空所有的历史记录

### ISSUE THREAD

**Issue by DuanShaoCheng** [nikissXI/nonebot_plugins#21]
账号更换时如果保留上个账号的记录会报错，如何解决这个问题，我删掉了talk_with_chatgpt.json 但是好像没有什么用处

**Comment by nikissXI** [comment]
报的什么错，给个截图啊

**Comment by DuanShaoCheng** [comment]
响应结果异常！
响应码: 404
响应内容: {"errorMessage":"The requested conversation cannot be found."}

**Comment by nikissXI** [comment]
看来是判断没写好，我改改

**Comment by nikissXI** [comment]
更新0.4.2就行了
