### ISSUE TITLE
ChatGPT插件能不能加个选项让所有连接上的go-cqhttp都相应

### ISSUE THREAD

**Issue by KudouShinnyan** [nikissXI/nonebot_plugins#22]
如题, 号码算是错开加群的所以不要担心一个群重复回复, 配置了 talk_with_chatgpt_bot_qqnum_list = [号码1, 号码2] 这样子貌似仍然只有号码1相应, 要是能加个开关所有连接上的go-cqhttp都相应就挺好的, 或者比如可以改成把talk_with_chatgpt_bot_qqnum_list这一项的值设置为all让所有QQ生效也不错

**Comment by nikissXI** [comment]
ee

**Comment by nikissXI** [comment]
加上了，版本号0.4.3。我直接改代码还没测试过的，你测试一下能不能用，使用方法看readme

**Comment by KudouShinnyan** [comment]
> 加上了，版本号0.4.3。我直接改代码还没测试过的，你测试一下能不能用，使用方法看readme

可以用了, 阿力嘎多
