### ISSUE TITLE
ChatGPT插件能不能加个配置选项让包含指定的关键字不响应

### ISSUE THREAD

**Issue by KudouShinnyan** [nikissXI/nonebot_plugins#23]
比如莪用的是zhenxun bot , 在发 "真寻帮助" 的时候ChatGPT插件也响应了 "帮助" , 要是加个如题的配置选项的话莪把 "真寻" 加入关键字应该就能解决

**Comment by nikissXI** [comment]
但是，我chatgpt插件并没有“帮助”这个命令

**Comment by nikissXI** [comment]
而且我这个chatgpt插件，所有触发命令都可以进行修改的，如果是命令冲突了，你改成不冲突的就行

**Comment by KudouShinnyan** [comment]
> 但是，我chatgpt插件并没有“帮助”这个命令

(指的是向ChatGPT发送 "帮助" 的文字消息)

**Comment by nikissXI** [comment]
你是说，在与chatgpt对话的时候，如果发送了“帮助”，其他插件会响应？

**Comment by KudouShinnyan** [comment]
> 你是说，在与chatgpt对话的时候，如果发送了“帮助”，其他插件会响应？

反过来了, 比如zhenxun bot 的帮助命令是 "真寻帮助" , 莪并没有把ChatGPT的前缀设置为 "真寻" , 但它在发送机器人帮助的同时ChatGPT又响应了 "帮助" 两个字的回复

**Comment by nikissXI** [comment]
能不能给截图，不知道你在说啥

**Comment by nikissXI** [comment]
你去.env，加上talk_with_chatgpt_talk_at = false，禁止tome触发应该就可以了

**Comment by KudouShinnyan** [comment]
> 能不能给截图，不知道你在说啥

用的机器人是这个https://github.com/HibiKier/zhenxun_bot
显示机器人菜单的默认命令是 "真寻帮助"
这里莪在.env.dev文件把机器人昵称改了所以是 "夏露夏帮助"
![Screenshot_20230531-110931_QQ](https://github.com/nikissXI/nonebot_plugins/assets/68854981/fa87f1ea-6020-4f65-b51c-36e93590ac2a)

**Comment by nikissXI** [comment]
talk_with_chatgpt_talk_at = false
刚我问了别的佬，是因为昵称触发的
把这个配置加上应该就可以了，to_me就不触发了

**Comment by KudouShinnyan** [comment]
> talk_with_chatgpt_talk_at = false 刚我问了别的佬，是因为昵称触发的 把这个配置加上应该就可以了，to_me就不触发了

(不能在不关掉@的情况让昵称不触发吗)

**Comment by nikissXI** [comment]
> > talk_with_chatgpt_talk_at = false 刚我问了别的佬，是因为昵称触发的 把这个配置加上应该就可以了，to_me就不触发了
> 
> (不能在不关掉@的情况让昵称不触发吗)

不能，你可以选择修改触发命令talk_with_chatgpt_talk_cmd。
因为用的on_message，我用block会把你插件都炸掉。
要么你自己去修改我插件的源码再使用。
或者，用别的gpt插件
