### ISSUE TITLE
之前0.4.3版能正常用, 换成0.6.0之后报错并且机器人中止运行了

### ISSUE THREAD

**Issue by KudouShinnyan** [nikissXI/nonebot_plugins#26]
中止运行之前出现如图报错
![image](https://github.com/nikissXI/nonebot_plugins/assets/68854981/bb266ba2-c697-4fec-8dce-bf7d0de90557)

**Comment by nikissXI** [comment]
把旧的data/talk_with_chatgpt.json删掉，新版的数据格式改了
