### ISSUE TITLE
话说ChatGPT的回复能不能以转发消息的形式发送

### ISSUE THREAD

**Issue by KudouShinnyan** [nikissXI/nonebot_plugins#27]
如题, 以文字消息有时候会被觉得刷屏了会比较反感, 以图片消息能一定程度解决但也不太完美, 要是能以转发消息的形式就好了, 就像图片的塔罗这样以转发消息形式回复
![Screenshot_20230614-182804_QQ](https://github.com/nikissXI/nonebot_plugins/assets/68854981/e9d6f8d8-f731-4700-bedd-b6f9a68444aa)

**Comment by nikissXI** [comment]
文字内容转发吗？
