### ISSUE TITLE
设置预设名或内容为bot昵称时不能识别

### ISSUE THREAD

**Issue by laiyoi** [nikissXI/nonebot_plugins#28]
当设置预设名或内容时回复bot昵称结果会没有![image](https://github.com/nikissXI/nonebot_plugins/assets/117524251/282afc10-5d6c-4682-b750-fff1b5a083bb)
![image](https://github.com/nikissXI/nonebot_plugins/assets/117524251/6a150541-289e-429e-906a-96a3a53ae542)
![image](https://github.com/nikissXI/nonebot_plugins/assets/117524251/9c297e4d-40b1-4b19-aff2-4542a7aeb273)
如果是bot的昵称加上别的昵称部分会被删除
![image](https://github.com/nikissXI/nonebot_plugins/assets/117524251/a83ac0a3-9590-4315-ac13-2577eaf6d3a0)

**Comment by nikissXI** [comment]
那就不要用bot昵称~
