### ISSUE TITLE
无法从poe服务器上获取回复

### ISSUE THREAD

**Issue by F1Justin** [nikissXI/nonebot_plugins#32]
登录正常，代理也正常，但回复不正常

`08-05 13:50:11 [SUCCESS] nonebot | OneBot V11 985393579 | [message.group.normal]: Message 1500476697 from *****@[群:****] '/talk hi'
08-05 13:50:11 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_talk_with_poe_ai)
08-05 13:50:12 [INFO] nonebot_plugin_talk_with_poe_ai | Succeed to subscribe
08-05 13:50:15 [ERROR] nonebot_plugin_talk_with_poe_ai | Failed to get bot chat_data from https://poe.com/_next/data/K5VTc2sxg7CyZETixuUnM/sXi5PA3liAIe9trzSLFL.json`

**Comment by nikissXI** [comment]
那你在网页创建过bot没

**Comment by F1Justin** [comment]
设置prompt后正常了，不过感觉prompt设置的步骤有点冗长，希望能改进）
