### ISSUE TITLE
talk_with_chatgpt 响应码429 It is recommended to upgrade to the latest PandoraNext:

### ISSUE THREAD

**Issue by Loss-of-time** [nikissXI/nonebot_plugins#41]
![image](https://github.com/nikissXI/nonebot_plugins/assets/51469672/041f8d6b-2632-4b01-8285-894d1ad74df6)

**Comment by nikissXI** [comment]
是突然不行还是？

**Comment by Karmau-Git** [comment]
我的也是这样

**Comment by 1296lol** [comment]
昨天11:23正常，11:24就开始报这个错

**Comment by 1296lol** [comment]
昨天11:23正常，11:24就开始报这个错

**Comment by nikissXI** [comment]
先自建反代解决，readme里有

之前的反代服务开发者说明天加上

**Comment by nikissXI** [comment]
使用潘多拉next的反代，具体看readme
