### ISSUE TITLE
nonebot_plugin_talk_with_chatgpt-6.4 响应结果异常 502

### ISSUE THREAD

**Issue by Karmau-Git** [nikissXI/nonebot_plugins#42]
已配置潘多拉next,api可在网页正常打开,access token有效
![image](https://github.com/nikissXI/nonebot_plugins/assets/118444525/35d43f20-3e71-469c-a991-65c16db80beb)
![image](https://github.com/nikissXI/nonebot_plugins/assets/118444525/3e9930bf-aa70-4f74-b4a3-f337289a040b)
![image](https://github.com/nikissXI/nonebot_plugins/assets/118444525/cd139461-a6e1-467e-b671-3bb8bc7ce1b6)

**Comment by nikissXI** [comment]
用潘多拉的话不需要走代理的，你这情况这样子不好排查，你进反馈群联系吧，比较好回复
