### ISSUE TITLE
管理员的qq号能否支持填写多个

### ISSUE THREAD

**Issue by RyanJiang184** [nikissXI/nonebot_plugins#43]
整合包完结之后经常要换，但是只有一个人能编辑，导致修改不够及时。管理员的qq号能否支持填写多个。
例如：# 管理员的QQ号（别问我为什么要另外写）
mc_status_admin_qqnum = [114514,1919180]

**Comment by nikissXI** [comment]
行，已更新，0.3.1版本支持了
