### ISSUE TITLE
无法返回服务器icon图片

### ISSUE THREAD

**Issue by thankU-ubi** [nikissXI/nonebot_plugins#6]
返回了一串base64代码

[CQ:image,file=base64://iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAKX0lEQVR4Xu1be2xT1xlPgQDiNY3H2IMVtrUaDUkcB9ACJJTyTAusHYU+6AaBjK2FrRpJSCgM1rSq1CIoSGhMBVGpLUhrURnqGK3SkgKdVCHKCuVVKIQkdvy2r33te52wP377vnN9jX3tQELtm67wx0/X95zvHN/vd77H+c61c8KKH+GIRAjFEERYCUC0xxHQ2nXo/eKex/D4riOkSJAF/FDDbkTDHmoL0H2QoD1HJByEKkt01WU18PhIDHobf1bCqd/TFeRoH3RF+CoZCDAoL+S5P7E9deKbgR9cvXQF0QsXEJXdYr6QIECbU1fKqKgO43xMlLGtK8hJXkXDyvO9aO9E0RS5G4OVYCWjvLofNcJWNgMtUx+AevhjyCEJAXoOzTr8BG1O48qnW+lEme4iRgCDvzCBAHGvkxMjKPZQGmKuINp1N7oZQqSAF+Ej78FWMg2+Aiv8hcVwTJ2F8L8/oH6/RoDqJYV8ggQjAbpF6HMmWsitkBBzgQQI8zcomuga8fZE37+xBciqG8Eo+bochHL4MJonTYKvcBycRflwWQsgFeajdXoplE8O4xpZR5hkw1EPwiqNV4MaEpQzKnsriuvI6dyEdcVj1hGPB3q/HjPSuIYBbNKRsANqYwPaJs2glS+Eo7gIrqpquFdXwTm+CL6icWidUkbu0IBoyCVWX1c+omgwKp4J5MSV72zVk+KCUcZoLcmQI+zzIbRL9PmjBtgmlcFTkEfKF8D//BqokhuKV4Jv/Qa0FZM1WMairXQa5MZG6gtCUkNCcSVGQOLctxr0jMi5nvoSFUxsS4SBgMS+lMk5qocQjbghf3wQzpKZCFmL4bVa4XphA6L+JgTI3ANyBO3+Njg2/BkOixVeSxEcZQ9RTGiAqpAbKDLNQcEvkqy0iAcZICE1CIqOGNt6PIjHBcNq66QkEBMhGTUcoKsf0SD1Hz2ElskltPIFsFsscNc/jw6fF0F6eIlJCvsQlgNod3vh3LgeLVaSIaKayyYj/MkhERMU1Y8OmlPheRNJyAwBqY1dRxrzVzTlwxEfgsc+hL3kfrgo4LkKJyBQ/xI6vE6ESKEgkRciGZZTZZYna5FtcP+lHjZLCdxFBXCVTEXoWAPCHTSnypsmJsH4DF8PX5OAdOCHDEF1OdBUOh2eovvIt/PgXf5b/Fei1KZGSKaNfNxFSmkBUoBSn0pktEtOOJdVEgF58BNaZ8yBEnITqZxCk9Ne6nd3H1kgQKKVJL/1+9FWsQRBivYe61jY583FtYun0RHwwr6uDs2/WYqOZjuCbClqLN+T60UvnIDtwdlwUkD0WorRurwCwQCRJSfn+28wAQGxmuGIDNX2FexLl1Oay4edIr993iwEKpbCUzyRkA/b2nUI08ZIJhIiZN7quS9hf2QeHNb7aEwBkbQCEfsV2iGSy6jO/xcCriMSlnGt7QqaKpbBVTyBglshmbUFfmsRWqZNRuj4EUpxpDwRIJ8/havzfwUvpUmpsBCtlZWIkvIyuVOISU0XbzKA7BJAJq1SFI+22nCVVtM9vlAo3zZ1CuQjB9BBwS9Kynd8cQbN8+bDbZlARFHwW/Y02ltbKTsEKUvQapN1MIzzZwJZJUCDlmY77OfhqXgCLTOmi8iu0P5AjZCrnP8PHL98GBKtvJ9T5ZLH0e65DC6LeSPFc2Qq56eDCQSwv1JmIGXbg05EvW3C75WIA+FPj6O5fC4FyYnwUl3gWPI7qPYmSAoHxuQ5skWCKQQk1+9Bkc6ix4/hyv1TqAYoot3heDStWI52R5MIhlwVimCawWDXGUwhwAiODc5t28nfqQiiXZ9tySpcc7bSvkDbVUbE1vpbTYAE19atsE8ohH2iBcrJkxQPuOiRaP9P7qIyCcny2TB/Ro8QoPDO7/B+tK56Bm3PVuOa3U6Ka8obCdBPgcQuMAsk9AgBrFS7yoHRDyVKGYIU0y1AR4oFpJknE+gxAhS91k+o+eN9XP+nGZcNmE6Az+/CwkULMKd8FmbPmRm/Llz0CBwUCFlGnAClGdsZjIcl3YHpBDS3XEaf3N5YsOBhPLPy91i56mk88eRj6NcvF6dOfyZ2fN0noPvvJnT0DAF9euPzUyeEoiq5wMVL5wQpVqsF9rYWIiF1XLbQIwT07t1LrDbfK7R6Fy+eQ27fPhjyncEoLZ0Cp8thGgk9Q0CfXjh9+qRQkg86zp8/i/79+2HfvrcxfPhQlD84B36/O2VsNmA+Ac2aC4yfUISZM2dg1qyZKCkpQW5uLi599SX+ceBd9Op1F557rlZkCOP4TMN0AqSgF/UvbMTatWvw6MIFqKS6f/36ddRWDxeZ/vz5czHy+9/DmTOfp4zNBkwngBGS/ZAkP+699x6srvoTuUJQ4A9/XImBAwfg0KGDVDHeemrrDnqEAE51Xp8bw0cMwyubXhbKv7p1C8WG3ti16zVxbxyTLZhOACvPccBHBAyjgLdly2a8s+/v6Ns3l/y+jtJiWATGrrxyywRMJYD9fwXV/SNo5VtarmLYsKHYSiu/cNGjWPzU48I1FEUW4JLZOD4bMI2AgOTBk4sfw6BBA/D66zvh9jgxdNh3BQFS0CeUvy6vv61KnSfTMIUANvuamtXoS9vdt9/ZK3aAHAPYBbZuezVeCGngE6FvEQGs/Gs7/0rK9yFlN8dXOpmAhHwv3jVqJ0LGubKBrBPAKC2bhLxxY+HxOuJtHq9LELBNECAjvupJb5yzT0LWCWALeP+Df2LwkEGwWPLR2Ngg2hxOOwZSPNi1a2dC1Gd08iY6S8g6ATpOfPYpJk/5hXCFysoKqgmaROrbu/ct3MpP7TIF0whg8Mq/8eZubN7yCi5fvkR7/l54d/8+3DYE6ODDjstXNAIOHNgPWTYn4qdDjxDAVZ7N3iJK4D173qTS12ta/W+E6QTwHqDhw/dx8F/viXOBhVQRlpfPTpEzC6YTwHFgzJi7UVu3BkePNqKKqsGCwvwUObNgOgE2+1VxALp79y6R/6trqpCfn5ciZxZMJYBXn/cBfCJ09uwXgoCNGzfgZ/f81FALmAdTCWDs+Nt2UQXyVpjT34sv1uPu0T+mTGDOxscIUwlgC6iqflaYfEjmthA2bXoZo0b9CKEQ/2QudUy2YSoBXPXxC5GH5pZD/xX6jh3bMXLkCPgD5pwCG5HDpscHFXFIPnFexzV6Ujvfczv3J7UnjtXO+lLHagjSKj8wfRqe+vVi+hwQeGvPG6JO0F+L6b8Hug5u084MU/uM0OWM83Q+R05e3s8xmtKSjjE/YYyOXTOPAQP7Y8iQwfH7H/xwJO0H7qI4MCpF9jroecZ09Zm6KqchZ8PGdVhTW4VagRqRn+tq61DH17rqGGpi97WxK9/rfV2VSezXsYa+r4a+v5quxvnSjeHPOjqZv5vPnsP7ck5BGsgs+BeZNzUjY19X+o0yMbmIn3aHWvl7Y/mQYazRnDv7fv7cWV9AC4KJDcYgkT2k+Ul+ikwiuGDS/76jwyjTfZiaBZIRqwDjhx9dIV8/NMncmWEPEvDNwB0CjA23G+4QYGy43XCHAGPD7YbbnoD/ATE3lgD70c44AAAAAElFTkSuQmCC,cache=true,proxy=true]
名称：来了 【1.19.2】
在线：0/50  延迟：38ms
◤ 没人在线 ◢

**Comment by nikissXI** [comment]
你这个服务器地址给一下，你顺便测试一下其他的服务器，我测试了十几个服务器都没这问题哇

**Comment by nikissXI** [comment]
> > 你这个服务器地址给一下，你顺便测试一下其他的服务器，我测试了十几个服务器都没这问题哇

收到，现在测试

**Comment by thankU-ubi** [comment]
![image](https://user-images.githubusercontent.com/104612463/213715377-0365b44a-7888-460c-b92b-b058b4a698a3.png)
![1OWH(~Q$0%FW9PRK4UKE~RP](https://user-images.githubusercontent.com/104612463/213715411-06813bde-3383-4bc5-8e11-0fec8140ce23.png)

**Comment by nikissXI** [comment]
![AFADE}0NE(0X3U3@}JL(G~Y](https://user-images.githubusercontent.com/31379266/213715687-a97a52e6-7975-4e8a-b4a4-10d5f9025c7f.png)
我这测试ok的？？？
你python版本，gocq版本，nonebot版本都给一下

**Comment by thankU-ubi** [comment]
![image](https://user-images.githubusercontent.com/104612463/213716442-0aa4b4c5-ccf4-48e9-bdd9-a1adc3a38429.png)
cqhttp是RC4 
nonebot是RC3 虚拟环境
py310

**Comment by nikissXI** [comment]
嘶。。。莫非是你用的gocq插件版的问题

**Comment by thankU-ubi** [comment]
直播通知都能正常发送带图消息的
![image](https://user-images.githubusercontent.com/104612463/213717159-b2e8e318-4224-4443-8427-96682a331e3e.png)

**Comment by thankU-ubi** [comment]
对了 这个服务器地址是用的腾讯云服务器做的frp 有没有可能是这个原因

**Comment by nikissXI** [comment]
我更新了插件版本，0.2.5，我把图标发送方式从base64改为BytesIO了，你现在再试试。可能是gocq插件版不支持base64图片发送。

**Comment by thankU-ubi** [comment]
好像还是不行 😂返回的还是base码

**Comment by nikissXI** [comment]
> 好像还是不行 😂返回的还是base码

插件现在是什么版本，是最新版本吗，最新版本已经不返回base64编码了

**Comment by thankU-ubi** [comment]
![image](https://user-images.githubusercontent.com/104612463/213728550-010b9a24-18e7-4acd-9b53-c3856738b96a.png)
![image](https://user-images.githubusercontent.com/104612463/213728996-77477a92-ea54-4d4f-a815-e954714ff043.png)
