### ISSUE TITLE
发送菜谱不知道为什么没有反应

### ISSUE THREAD

**Issue by Kimaru-bili** [nikissXI/nonebot_plugins#7]
配置文件
![image](https://user-images.githubusercontent.com/40233772/213766253-6ae89d11-5d2b-45d5-bce3-739d34e07ff0.png)
日志
![image](https://user-images.githubusercontent.com/40233772/213766380-49826dc8-7d03-44d0-8b2f-d12c32a37f2c.png)

**Comment by nikissXI** [comment]
nya_cook_user_list = [1234, 5678]
应该是这样写，我readme里忘记把类型注解删了
已修改readme里的错误，抱歉

**Comment by nikissXI** [comment]
可以了吗

**Comment by Kimaru-bili** [comment]
我还没试 等一下我试试看

**Comment by Kimaru-bili** [comment]
好使了 感谢（麻烦您了
![image](https://user-images.githubusercontent.com/40233772/215343117-dda591e5-c07c-46bb-94ef-3160f131dfa5.png)
