### ISSUE TITLE
图图插件api导入问题

### ISSUE THREAD

**Issue by doiss** [nikissXI/nonebot_plugins#8]
![TJZF8P0_00}U%R8LH594N E](https://user-images.githubusercontent.com/97965580/215799549-52eb94ae-195f-4bff-adad-5e13c22157bb.png)
![848103501-238868778-AA2EC5D04E555A36CFBCAC7DB0A07795](https://user-images.githubusercontent.com/97965580/215799577-bf27b641-9bfc-4f8c-9e2e-7e28974d81ab.jpg)
测试api时报错

**Comment by nikissXI** [comment]
如果你不配置代理就把tutu_socks5_proxy删了，不需要的配置就不要填

**Comment by doiss** [comment]
az QAQ 我去试试

**Comment by doiss** [comment]
好了Y(^o^)Y感谢大佬！
![930C0003DB631ADA0E04A0DE1287606F](https://user-images.githubusercontent.com/97965580/215803766-9eec6b3a-bcf1-4444-9a93-90ee1dc17f67.gif)
